### ISSUE TITLE
Missing app.less

### ISSUE THREAD

**Issue by vrassouli** [deregtd/DICOMSharp#1]
Hello and thank you for the great job you have done :-)

compilerconfig.json:
`[
  {
    "outputFile": "css/app.css",
    "inputFile": "css/app.less"
  }
]`

the input file 'app.less' is missing!

**Comment by deregtd** [comment]
Interesting -- I don't use the in-visual-studio compiler system anymore, so that's probably just a remnant.    In theory, just running "npm run start" should get the whole web build pipeline running (after an npm install, of course.)

**Comment by deregtd** [comment]
Removed this in 665ece28187d012d321d6ef6a6cfa99e7dfac078
