### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by hammoo** [deregtd/DICOMSharp#3]
Hi 

I wanted to know one thing. Instead of using IIS can i use the Apache webserver to host the PHP code???

--Hammad

**Comment by deregtd** [comment]
Sorry, the main DICOM code is all in C#, which requires IIS.

**Comment by hammoo** [comment]
Thanks for your prompt reply. If DICOM Server is in C# then why we are needing PHP extensions in IIS??

**Comment by deregtd** [comment]
You don't.  There's no PHP in the project.  Are you confusing this with the older MyFreePACS software?

**Comment by hammoo** [comment]
I am using this URL(http://www.pacssoft.com/?page=myfreepacs_setup_install) in setting up the PACS Server. 

If possible can you please share the latest software exe and steps how to install and configure.

**Comment by deregtd** [comment]
Those are the latest instructions and software version.  I haven't touched MyFreePACS in ~5 years.

DICOMSharp is a different project, which powers PSPACS, which has its own installation instructions: http://www.pacssoft.com/?page=pspacs

**Comment by hammoo** [comment]
Thanks. Will you please share the steps and pre-requisites for installation and one thing more is MyFreePACS is PHP based?? Can i deploy it using Apache webserver?

**Comment by deregtd** [comment]
All of the steps are on the page I linked.  I have never tried it on apache, you'll be on your own there.

**Comment by hammoo** [comment]
It means using MyFreePACS i can deploy it on LINUX as well as windows???

**Comment by deregtd** [comment]
I don't know.  I've never tried, and I know of no one else that has either.

**Comment by hammoo** [comment]
OKie. thanks. I will give it a try and update you

**Comment by hammoo** [comment]
One last thing i forgot to ask, is it possible to use the viewer of DICOMSharp for viewing of images to pull images from some other PACS???

DO DICOMSharp support WADO?? If yes please share and guide how to setup.

**Comment by deregtd** [comment]
For PSPACS and MyFreePACS, you have to push images into the server and view them from there.  There are sample apps in the DICOMSharp repo for retrieving from other systems as a horrible mini viewer, but they're not in any usable state other than demos for coders.  I don't know what WADO is.
